#!/usr/bin/env python3
"""
generate_report_draft.py

Populate a Markdown report skeleton, modeled on this repository's
Executive Summary template (osint-templates/specialized-formats/
executive-summary.md), from a structured findings file (JSON or CSV).

This script performs NO analysis. It organizes findings data you provide
into a consistent report structure, and leaves sections that require
human analytical judgment (bottom line, recommendations, limitations)
as explicit, clearly marked placeholders. See
osint-tools/ai-powered-tools/automated-reporting/README.md for the
principle this script follows: automate structure, not substance.

Requirements:
    Python 3.8+ (standard library only, no third-party packages required)

Usage:
    python generate_report_draft.py --input sample_findings.json --output draft_report.md
    python generate_report_draft.py --input findings.csv --output draft_report.md

Input JSON structure (see sample_findings.json for a full example):
    {
        "case_id": "...",
        "subject": "...",
        "prepared_for": "...",
        "prepared_by": "...",
        "date": "...",
        "classification": "...",
        "full_report_reference": "...",
        "findings": [
            {
                "finding": "Concise statement of the finding",
                "confidence": "High | Medium | Low",
                "reasoning": "One-line reasoning for the confidence level",
                "source": "Human-readable source name",
                "source_url": "https://..."
            }
        ]
    }

Input CSV structure (one row per finding; header row required):
    finding,confidence,reasoning,source,source_url
"""

import argparse
import csv
import json
import sys


def load_findings_json(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    data.setdefault("findings", [])
    return data


def load_findings_csv(path: str) -> dict:
    findings = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            findings.append({
                "finding": row.get("finding", "").strip(),
                "confidence": row.get("confidence", "").strip() or "Not specified",
                "reasoning": row.get("reasoning", "").strip(),
                "source": row.get("source", "").strip(),
                "source_url": row.get("source_url", "").strip(),
            })
    # CSV input has no case-level metadata fields, so those are left as
    # placeholders for the analyst to fill in directly in the output file.
    return {"findings": findings}


def build_markdown(data: dict) -> str:
    case_id = data.get("case_id", "[Case/Project ID]")
    subject = data.get("subject", "[Investigation subject/entity]")
    prepared_for = data.get("prepared_for", "[Executive/stakeholder name or committee]")
    prepared_by = data.get("prepared_by", "[Analyst/team name]")
    date = data.get("date", "[Date]")
    classification = data.get("classification", "[Public / Internal / Confidential]")
    full_report_ref = data.get("full_report_reference", "[Reference to the complete underlying report and its location]")
    findings = data.get("findings", [])

    lines = []
    lines.append("# Executive Summary Template")
    lines.append("")
    lines.append("> DRAFT — auto-generated structure from findings data. Every placeholder in")
    lines.append("> brackets below requires human analyst input before this document is used or")
    lines.append("> distributed. This draft was not generated by, and does not represent, an")
    lines.append("> independent analytical assessment.")
    lines.append("")
    lines.append("## Document Header")
    lines.append("")
    lines.append(f"**Subject:** {subject}")
    lines.append(f"**Prepared For:** {prepared_for}")
    lines.append(f"**Prepared By:** {prepared_by}")
    lines.append(f"**Date:** {date}")
    lines.append(f"**Classification:** {classification}")
    lines.append(f"**Full Report Reference:** {full_report_ref}")
    lines.append(f"**Case/Project ID:** {case_id}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 1. Purpose of Investigation")
    lines.append("")
    lines.append("[REQUIRES HUMAN INPUT: one to two sentences stating why this investigation was conducted.]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 2. Bottom Line Up Front")
    lines.append("")
    lines.append("[REQUIRES HUMAN INPUT: a single, clear paragraph stating the most important conclusion. "
                  "This script does not draw conclusions from findings data.]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 3. Key Findings")
    lines.append("")
    if findings:
        for item in findings:
            finding_text = item.get("finding", "[Finding not specified]")
            lines.append(f"- {finding_text}")
    else:
        lines.append("[No findings were provided in the input file.]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 4. Confidence and Caveats")
    lines.append("")
    lines.append("| Finding | Confidence Level | Reasoning |")
    lines.append("|---|---|---|")
    if findings:
        for item in findings:
            finding_text = item.get("finding", "[Finding not specified]")
            confidence = item.get("confidence", "Not specified")
            reasoning = item.get("reasoning", "[REQUIRES HUMAN INPUT]")
            # Escape pipe characters so they don't break the Markdown table.
            finding_cell = finding_text.replace("|", "\\|")
            reasoning_cell = reasoning.replace("|", "\\|")
            lines.append(f"| {finding_cell} | {confidence} | {reasoning_cell} |")
    else:
        lines.append("| [No findings provided] | | |")
    lines.append("")
    lines.append("**Notable Limitations:** [REQUIRES HUMAN INPUT: any significant gaps or caveats.]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 5. Risk and Impact Assessment")
    lines.append("")
    lines.append("- **Overall Risk Level (if applicable):** [REQUIRES HUMAN INPUT]")
    lines.append("- **Primary Risk Driver:** [REQUIRES HUMAN INPUT]")
    lines.append("- **Business/Operational Impact:** [REQUIRES HUMAN INPUT]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 6. Recommendations")
    lines.append("")
    lines.append("[REQUIRES HUMAN INPUT: priority-ordered, actionable recommendations. "
                  "This script does not generate recommendations from findings data.]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 7. Source List")
    lines.append("")
    sources_seen = set()
    if findings:
        for item in findings:
            source = item.get("source", "").strip()
            source_url = item.get("source_url", "").strip()
            key = (source, source_url)
            if source and key not in sources_seen:
                sources_seen.add(key)
                if source_url:
                    lines.append(f"- {source}: {source_url}")
                else:
                    lines.append(f"- {source}")
    if not sources_seen:
        lines.append("[No sources provided]")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*This draft was generated automatically from structured findings data and requires "
        "full analyst review, verification against source material, and completion of all "
        "bracketed sections before distribution, per osint-templates/operational-planning/"
        "investigation-workflow.md.*"
    )
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a draft Markdown report structure from a structured findings file."
    )
    parser.add_argument("--input", required=True, help="Path to a findings .json or .csv file")
    parser.add_argument("--output", required=True, help="Path to write the generated Markdown draft")
    args = parser.parse_args()

    if args.input.lower().endswith(".json"):
        data = load_findings_json(args.input)
    elif args.input.lower().endswith(".csv"):
        data = load_findings_csv(args.input)
    else:
        sys.exit("Input file must be .json or .csv")

    markdown = build_markdown(data)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(markdown)

    finding_count = len(data.get("findings", []))
    print(f"Draft report written to {args.output} ({finding_count} finding(s) incorporated).")
    print("This is a structural draft only — every bracketed placeholder requires human input "
          "before use, per this folder's README.")


if __name__ == "__main__":
    main()
